# Generated by Django 4.1.5 on 2023-06-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resttapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default='Image/None/Noimg.jpg', upload_to='Images/'),
        ),
    ]
